### ISSUE TITLE
Python: improper re-export of openapi generated types

### ISSUE THREAD

**Issue by svix-frank** [svix/svix-libs#135]
pyright just added a new check `reportPrivateImportUsage` which fails for our re-exported types in API

https://github.com/microsoft/pyright/commit/9035f64c71922a9bd1fbf36a990ba24353912c72

**Comment by tasn** [comment]
I think we can just fix these to import from the correct modules (the .model one). 

It's literally just fixing the few errors in https://github.com/svix/monorepo-private/runs/3601480481?check_suite_focus=true no?

**Comment by tasn** [comment]
I think we can just fix these to import from the correct modules (the .model one), no?
