### ISSUE TITLE
Health endpoint not included in Ruby bindings

### ISSUE THREAD

**Issue by pjohnmeyer** [svix/svix-libs#171]
**Expected Behavior**

```ruby
irb(main):001:0> require 'svix'
=> true
irb(main):002:0> svix = Svix::Client.new('api-key')
=> #<Svix::Client:0x00007fc5d825e4a0 @application=#<Svix::ApplicationAPI:0x00007fc5d825d848  ...
irb(main):003:0> svix.health.get
=> nil # I'd actually like endpoints like this and deletes that return 204 to return something more useful than nil, but this is the pattern I expect currently
```

**Actual Behavior**
```ruby
irb(main):003:0> svix.health.get
Traceback (most recent call last):
        2: from (irb):3
        1: from (irb):4:in `rescue in irb_binding'
NoMethodError (undefined method `health' for #<Svix::Client:0x00007fc5dd831990>)
```

**Comment by svix-frank** [comment]
Hey @pjohnmeyer, thanks for the report!  To keep the libraries as minimal as possible we chose not to expose this endpoint in any of our libraries.  What's your use case for this endpoint?  I hadn't expected any users to request it as we really only use it for our internal monitoring.  We can consider adding it to the libs if you have a need for it.

**Comment by pjohnmeyer** [comment]
@svix-frank the use case was for my own automated monitoring. Currently our application sends messages fairly infrequently, so pinging the API periodically to know it's alive is useful so we can be alert for possible problems.

I can of course also use `application.get` for this purpose. I am okay with that approach if that is your recommendation.

**Comment by svix-frank** [comment]
Most of our customers use the `Subscribe to Updates` feature on our status page (https://status.svix.com/) for monitoring like this, would that be sufficient for your use case or is it lacking in some way?

**Comment by pjohnmeyer** [comment]
@svix-frank that's probably sufficient, thanks.
