### ISSUE TITLE
Python: Cleanup Generated Models

### ISSUE THREAD

**Issue by svix-frank** [svix/svix-libs#70]
Generated Models are created with arguments in alphabetical order eg `EventTypeIn("description", "name")` I don't love this, we probably want to wrap these models or see if we can generate them with named arguments

**Comment by tasn** [comment]
You can initialize them with named arguments. No? Anyhow, it's related to #67, we need to use @dataclass or something and fix this.

**Comment by svix-frank** [comment]
Don't think this is really needed anymore
