### ISSUE TITLE
Go: Add sensible default timeouts to HTTPClient

### ISSUE THREAD

**Issue by plarsson** [svix/svix-libs#97]
Also make it possible to configure your own instance of HTTPClient.

**Comment by svix-frank** [comment]
Hey @plarsson happy to add this, what would you consider "sensible"? For context looking at some of the giants, stripe-go has a default of 80 seconds (which seems long already), C# is 100 seconds, node is 2min.  Would you consider 60s a good default?

**Comment by plarsson** [comment]
yeah 60s is fine as defaults, just to make sure it never hangs infinite. I would probably configure it like 10 seconds if I can override it with my own client.

**Comment by svix-frank** [comment]
> yeah 60s is fine as defaults, just to make sure it never hangs infinite. I would probably configure it like 10 seconds if I can override it with my own client.

Awesome, I'll get this in ASAP. Yeah, we actually discussed ~10s internally but probably best to set it a bit high and let aware users like yourself set override as they see fit =)

**Comment by svix-frank** [comment]
@plarsson I've added this in https://github.com/svix/svix-libs/issues/97, will be making a new release shortly, please let me know if this is sufficient, or if there's anything else I can help with!

Thanks for the report!
